name: LaTeX Release

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: report/main.tex
          latexmk_use_xelatex: true

      - name: Check output
        run: ls

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: main-pdf
          path: main.pdf

      - name: Release
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            main.pdf
